<?php
$sql_result['create'] = $wpdb->query( "
CREATE TABLE IF NOT EXISTS `$currency_table_name` (
  `id` int unsigned NOT NULL auto_increment,
  `country` varchar(255) NOT NULL default '',
  `countrycode` char(2) default '',
  `currency` varchar(255) NOT NULL default '',
  `currencycode` char(3) NOT NULL default '',
  `available` tinyint(1) NOT NULL default 1,
  PRIMARY KEY  (`id`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 ;
");

$sql_result['insert'] = $wpdb->query( "
INSERT INTO `$currency_table_name` (`country`, `countrycode`, `currency`, `currencycode`,`available`) VALUES
(1, 'Afghanistan', 'AF', 'Afghanistan Afghani', 'AFA', 0),
(2, 'Albania', 'AL', 'Albanian Lek', 'ALL', 0),
(3, 'Algeria', 'DZ', 'Algerian Dinar', 'DZD', 1),
(4, 'American Samoa', 'AS', 'US Dollar', 'USD', 1),
(5, 'Andorra', 'AD', 'Euro', 'EUR', 1),
(6, 'Angola', 'AO', 'Angolan New Kwanza', 'AON', 0),
(7, 'Anguilla', 'AI', 'East Caribbean Dollar', 'XCD', 0),
(8, 'Antarctica', 'AQ', 'Dollar', 'ATA', 0),
(9, 'Antigua and Barbuda', 'AG', 'East Caribbean Dollar', 'XCD', 0),
(10, 'Argentina', 'AR', 'Argentine Peso', 'ARS', 1),
(11, 'Armenia', 'AM', 'Armenian Dram', 'AMD', 0),
(12, 'Aruba', 'AW', 'Aruban Guilder', 'AWG', 0),
(13, 'Australia', 'AU', 'Australian Dollar', 'AUD', 1),
(14, 'Austria', 'AT', 'Euro', 'EUR', 1),
(15, 'Azerbaijan', 'AZ', 'Azerbaijanian Manat', 'AZM', 0),
(16, 'Bahamas', 'BS', 'Bahamian Dollar', 'BSD', 0),
(17, 'Bahrain', 'BH', 'Bahraini Dinar', 'BHD', 1),
(18, 'Bangladesh', 'BD', 'Bangladeshi Taka', 'BDT', 0),
(19, 'Barbados', 'BB', 'Barbados Dollar', 'BBD', 0),
(20, 'Belarus', 'BY', 'Belarussian Ruble', 'BYB', 0),
(21, 'Belgium', 'BE', 'Euro', 'EUR', 1),
(22, 'Belize', 'BZ', 'Belize Dollar', 'BZD', 0),
(23, 'Benin', 'BJ', 'CFA Franc BCEAO', 'XOF', 0),
(24, 'Bermuda', 'BM', 'Bermudian Dollar', 'BMD', 0),
(25, 'Bhutan', 'BT', 'Bhutan Ngultrum', 'BTN', 0),
(26, 'Bolivia', 'BO', 'Boliviano', 'BOB', 1),
(27, 'Bosnia-Herzegovina', 'BA', 'Marka', 'BAM', 0),
(28, 'Botswana', 'BW', 'Botswana Pula', 'BWP', 1),
(29, 'Bouvet Island', 'BV', 'Norwegian Krone', 'NOK', 1),
(30, 'Brazil', 'BR', 'Brazilian Real', 'BRL', 1),
(31, 'British Indian Ocean Territory', 'IO', 'US Dollar', 'USD', 1),
(32, 'Brunei Darussalam', 'BN', 'Brunei Dollar', 'BND', 1),
(33, 'Bulgaria', 'BG', 'Bulgarian Lev', 'BGL', 0),
(34, 'Burkina Faso', 'BF', 'CFA Franc BCEAO', 'XOF', 0),
(35, 'Burundi', 'BI', 'Burundi Franc', 'BIF', 0),
(36, 'Cambodia', 'KH', 'Kampuchean Riel', 'KHR', 0),
(37, 'Cameroon', 'CM', 'CFA Franc BEAC', 'XAF', 0),
(38, 'Canada', 'CA', 'Canadian Dollar', 'CAD', 1),
(39, 'Cape Verde', 'CV', 'Cape Verde Escudo', 'CVE', 0),
(40, 'Cayman Islands', 'KY', 'Cayman Islands Dollar', 'KYD', 1),
(41, 'Central African Republic', 'CF', 'CFA Franc BEAC', 'XAF', 0),
(42, 'Chad', 'TD', 'CFA Franc BEAC', 'XAF', 0),
(43, 'Chile', 'CL', 'Chilean Peso', 'CLP', 1),
(44, 'China', 'CN', 'Yuan Renminbi', 'CNY', 1),
(45, 'Christmas Island', 'CX', 'Australian Dollar', 'AUD', 1),
(46, 'Cocos (Keeling) Islands', 'CC', 'Australian Dollar', 'AUD', 1),
(47, 'Colombia', 'CO', 'Colombian Peso', 'COP', 1),
(48, 'Comoros', 'KM', 'Comoros Franc', 'KMF', 0),
(49, 'Congo', 'CG', 'CFA Franc BEAC', 'XAF', 0),
(50, 'Cook Islands', 'CK', 'New Zealand Dollar', 'NZD', 1),
(51, 'Costa Rica', 'CR', 'Costa Rican Colon', 'CRC', 1),
(52, 'Croatia', 'HR', 'Croatian Kuna', 'HRK', 1),
(53, 'Cuba', 'CU', 'Cuban Peso', 'CUP', 0),
(54, 'Cyprus', 'CY', 'Cyprus Pound', 'CYP', 0),
(55, 'Czech Rep.', 'CZ', 'Czech Koruna', 'CZK', 1),
(56, 'Democratic Republic of Congo', 'CD', 'Francs', 'CDF', 0),
(57, 'Denmark', 'DK', 'Danish Krone', 'DKK', 1),
(58, 'Djibouti', 'DJ', 'Djibouti Franc', 'DJF', 0),
(59, 'Dominica', 'DM', 'East Caribbean Dollar', 'XCD', 0),
(60, 'Dominican Republic', 'DO', 'Dominican Peso', 'DOP', 1),
(61, 'East Timor', 'TP', 'Timor Escudo', 'TPE', 0),
(62, 'Ecuador', 'EC', 'Ecuador Sucre', 'ECS', 0),
(63, 'Egypt', 'EG', 'Egyptian Pound', 'EGP', 1),
(64, 'El Salvador', 'SV', 'El Salvador Colon', 'SVC', 1),
(65, 'Equatorial Guinea', 'GQ', 'CFA Franc BEAC', 'XAF', 0),
(66, 'Eritrea', 'ER', 'Eritrean Nakfa', 'ERN', 0),
(67, 'Estonia', 'EE', 'Estonian Kroon', 'EEK', 1),
(68, 'Ethiopia', 'ET', 'Ethiopian Birr', 'ETB', 0),
(69, 'Falkland Islands', 'FK', 'Falkland Islands Pound', 'FKP', 0),
(70, 'Faroe Islands', 'FO', 'Danish Krone', 'DKK', 1),
(71, 'Fiji', 'FJ', 'Fiji Dollar', 'FJD', 1),
(72, 'Finland', 'FI', 'Euro', 'EUR', 1),
(73, 'France', 'FR', 'Euro', 'EUR', 1),
(74, 'French Southern Territories', 'TF', 'Euro', 'EUR', 1),
(75, 'Gabon', 'GA', 'CFA Franc BEAC', 'XAF', 0),
(76, 'Gambia', 'GM', 'Gambian Dalasi', 'GMD', 0),
(77, 'Georgia', 'GE', 'Georgian Lari', 'GEL', 0),
(78, 'Germany', 'DE', 'Euro', 'EUR', 1),
(79, 'Ghana', 'GH', 'Ghanaian Cedi', 'GHC', 0),
(80, 'Gibraltar', 'GI', 'Gibraltar Pound', 'GIP', 0),
(81, 'Great Britain', 'GB', 'Pound Sterling', 'GBP', 1),
(82, 'Greece', 'GR', 'Euro', 'EUR', 1),
(83, 'Greenland', 'GL', 'Danish Krone', 'DKK', 1),
(84, 'Grenada', 'GD', 'East Carribean Dollar', 'XCD', 0),
(85, 'Guadeloupe (French)', 'GP', 'Euro', 'EUR', 1),
(86, 'Guam (USA)', 'GU', 'US Dollar', 'USD', 1),
(87, 'Guatemala', 'GT', 'Guatemalan Quetzal', 'QTQ', 0),
(88, 'Guernsey', 'GF', 'Pound Sterling', 'GBP', 1),
(89, 'Guinea', 'GN', 'Guinea Franc', 'GNF', 0),
(90, 'Guinea Bissau', 'GW', 'Guinea-Bissau Peso', 'GWP', 0),
(91, 'Guyana', 'GY', 'Guyana Dollar', 'GYD', 0),
(92, 'Haiti', 'HT', 'Haitian Gourde', 'HTG', 0),
(93, 'Heard Island and McDonald Islands', 'HM', 'Australian Dollar', 'AUD', 1),
(94, 'Honduras', 'HN', 'Honduran Lempira', 'HNL', 1),
(95, 'Hong Kong', 'HK', 'Hong Kong Dollar', 'HKD', 1),
(96, 'Hungary', 'HU', 'Hungarian Forint', 'HUF', 1),
(97, 'Iceland', 'IS', 'Iceland Krona', 'ISK', 0),
(98, 'India', 'IN', 'Indian Rupee', 'INR', 1),
(99, 'Indonesia', 'ID', 'Indonesian Rupiah', 'IDR', 1),
(100, 'Iran', 'IR', 'Iranian Rial', 'IRR', 0),
(101, 'Iraq', 'IQ', 'Iraqi Dinar', 'IQD', 0),
(102, 'Ireland', 'IE', 'Euro', 'EUR', 1),
(103, 'Isle of Man', 'IM', 'Pound Sterling', 'GBP', 1),
(104, 'Israel', 'IL', 'Israeli New Shekel', 'ILS', 1),
(105, 'Italy', 'IT', 'Euro', 'EUR', 1),
(106, 'Ivory Coast', 'CI', 'CFA Franc BCEAO', 'XOF', 0),
(107, 'Jamaica', 'JM', 'Jamaican Dollar', 'JMD', 1),
(108, 'Japan', 'JP', 'Japanese Yen', 'JPY', 1),
(109, 'Jersey', 'JE', 'Pound Sterling', 'GBP', 1),
(110, 'Jordan', 'JO', 'Jordanian Dinar', 'JOD', 1),
(111, 'Kazakhstan', 'KZ', 'Kazakhstan Tenge', 'KZT', 1),
(112, 'Kenya', 'KE', 'Kenyan Shilling', 'KES', 1),
(113, 'Kiribati', 'KI', 'Australian Dollar', 'AUD', 1),
(114, 'Korea, North', 'KP', 'North Korean Won', 'KPW', 0),
(115, 'Korea, South', 'KR', 'Korean Won', 'KRW', 1),
(116, 'Kuwait', 'KW', 'Kuwaiti Dinar', 'KWD', 1),
(117, 'Kyrgyzstan', 'KG', 'Som', 'KGS', 0),
(118, 'Laos', 'LA', 'Lao Kip', 'LAK', 0),
(119, 'Latvia', 'LV', 'Latvian Lats', 'LVL', 1),
(120, 'Lebanon', 'LB', 'Lebanese Pound', 'LBP', 1),
(121, 'Lesotho', 'LS', 'Lesotho Loti', 'LSL', 0),
(122, 'Liberia', 'LR', 'Liberian Dollar', 'LRD', 0),
(123, 'Libya', 'LY', 'Libyan Dinar', 'LYD', 0),
(124, 'Liechtenstein', 'LI', 'Swiss Franc', 'CHF', 1),
(125, 'Lithuania', 'LT', 'Lithuanian Litas', 'LTL', 1),
(126, 'Luxembourg', 'LU', 'Euro', 'EUR', 1),
(127, 'Macau', 'MO', 'Macau Pataca', 'MOP', 0),
(128, 'Macedonia', 'MK', 'Denar', 'MKD', 1),
(129, 'Madagascar', 'MG', 'Malagasy Franc', 'MGF', 0),
(130, 'Malawi', 'MW', 'Malawi Kwacha', 'MWK', 0),
(131, 'Malaysia', 'MY', 'Malaysian Ringgit', 'MYR', 1),
(132, 'Maldives', 'MV', 'Maldive Rufiyaa', 'MVR', 0),
(133, 'Mali', 'ML', 'CFA Franc BCEAO', 'XOF', 0),
(134, 'Malta', 'MT', 'Maltese Lira', 'MTL', 0),
(135, 'Marshall Islands', 'MH', 'US Dollar', 'USD', 1),
(136, 'Martinique (French)', 'MQ', 'Euro', 'EUR', 1),
(137, 'Mauritania', 'MR', 'Mauritanian Ouguiya', 'MRO', 0),
(138, 'Mauritius', 'MU', 'Mauritius Rupee', 'MUR', 1),
(139, 'Mayotte', 'YT', 'Euro', 'EUR', 1),
(140, 'Mexico', 'MX', 'Mexican Nuevo Peso', 'MXN', 1),
(141, 'Micronesia', 'FM', 'US Dollar', 'USD', 1),
(142, 'Moldova', 'MD', 'Moldovan Leu', 'MDL', 1),
(143, 'Monaco', 'MC', 'Euro', 'EUR', 1),
(144, 'Mongolia', 'MN', 'Mongolian Tugrik', 'MNT', 0),
(145, 'Montserrat', 'MS', 'East Caribbean Dollar', 'XCD', 0),
(146, 'Morocco', 'MA', 'Moroccan Dirham', 'MAD', 1),
(147, 'Mozambique', 'MZ', 'Mozambique Metical', 'MZM', 0),
(148, 'Myanmar', 'MM', 'Myanmar Kyat', 'MMK', 0),
(149, 'Namibia', 'NA', 'Namibian Dollar', 'NAD', 1),
(150, 'Nauru', 'NR', 'Australian Dollar', 'AUD', 1),
(151, 'Nepal', 'NP', 'Nepalese Rupee', 'NPR', 1),
(152, 'Netherlands', 'NL', 'Euro', 'EUR', 1),
(153, 'Netherlands Antilles', 'AN', 'Netherlands Antillean Guilder', 'ANG', 1),
(154, 'New Caledonia (French)', 'NC', 'CFP Franc', 'XPF', 0),
(155, 'New Zealand', 'NZ', 'New Zealand Dollar', 'NZD', 1),
(156, 'Nicaragua', 'NI', 'Nicaraguan Cordoba Oro', 'NIC', 0),
(157, 'Niger', 'NE', 'CFA Franc BCEAO', 'XOF', 0),
(158, 'Nigeria', 'NG', 'Nigerian Naira', 'NGN', 1),
(159, 'Niue', 'NU', 'New Zealand Dollar', 'NZD', 1),
(160, 'Norfolk Island', 'NF', 'Australian Dollar', 'AUD', 1),
(161, 'Northern Mariana Islands', 'MP', 'US Dollar', 'USD', 1),
(162, 'Norway', 'NO', 'Norwegian Krone', 'NOK', 1),
(163, 'Oman', 'OM', 'Omani Rial', 'OMR', 1),
(164, 'Pakistan', 'PK', 'Pakistan Rupee', 'PKR', 1),
(165, 'Palau', 'PW', 'US Dollar', 'USD', 1),
(166, 'Panama', 'PA', 'Panamanian Balboa', 'PAB', 0),
(167, 'Papua New Guinea', 'PG', 'Papua New Guinea Kina', 'PGK', 1),
(168, 'Paraguay', 'PY', 'Paraguay Guarani', 'PYG', 1),
(169, 'Peru', 'PE', 'Peruvian Nuevo Sol', 'PEN', 1),
(170, 'Philippines', 'PH', 'Philippine Peso', 'PHP', 1),
(171, 'Pitcairn Island', 'PN', 'New Zealand Dollar', 'NZD', 1),
(172, 'Poland', 'PL', 'Polish Zloty', 'PLN', 1),
(173, 'Polynesia (French)', 'PF', 'CFP Franc', 'XPF', 0),
(174, 'Portugal', 'PT', 'Euro', 'EUR', 1),
(175, 'Puerto Rico', 'PR', 'US Dollar', 'USD', 1),
(176, 'Qatar', 'QA', 'Qatari Rial', 'QAR', 1),
(177, 'Reunion (French)', 'RE', 'Euro', 'EUR', 1),
(178, 'Romania', 'RO', 'Romanian Leu', 'RON', 1),
(179, 'Russia', 'RU', 'Russian Ruble', 'RUR', 1),
(180, 'Rwanda', 'RW', 'Rwanda Franc', 'RWF', 0),
(181, 'Saint Helena', 'SH', 'St. Helena Pound', 'SHP', 0),
(182, 'Saint Kitts & Nevis Anguilla', 'KN', 'East Caribbean Dollar', 'XCD', 0),
(183, 'Saint Lucia', 'LC', 'East Caribbean Dollar', 'XCD', 0),
(184, 'Saint Pierre and Miquelon', 'PM', 'Euro', 'EUR', 1),
(185, 'Saint Vincent & Grenadines', 'VC', 'East Caribbean Dollar', 'XCD', 0),
(186, 'Samoa', 'WS', 'Samoan Tala', 'WST', 0),
(187, 'San Marino', 'SM', 'Italian Lira', 'ITL', 0),
(188, 'Sao Tome and Principe', 'ST', 'Dobra', 'STD', 0),
(189, 'Saudi Arabia', 'SA', 'Saudi Riyal', 'SAR', 1),
(190, 'Senegal', 'SN', 'CFA Franc BCEAO', 'XOF', 0),
(191, 'Seychelles', 'SC', 'Seychelles Rupee', 'SCR', 1),
(192, 'Sierra Leone', 'SL', 'Sierra Leone Leone', 'SLL', 1),
(193, 'Singapore', 'SG', 'Singapore Dollar', 'SGD', 1),
(194, 'Slovakia', 'SK', 'Euro', 'EUR', 1),
(195, 'Slovenia', 'SI', 'Slovenian Tolar', 'SIT', 0),
(196, 'Solomon Islands', 'SB', 'Solomon Islands Dollar', 'SBD', 0),
(197, 'Somalia', 'SO', 'Somali Shilling', 'SOD', 0),
(198, 'South Africa', 'ZA', 'South African Rand', 'ZAR', 1),
(199, 'South Georgia & South Sandwich Islands', 'GS', 'Pound Sterling', 'GBP', 1),
(200, 'Spain', 'ES', 'Euro', 'EUR', 1),
(201, 'Sri Lanka', 'LK', 'Sri Lanka Rupee', 'LKR', 1),
(202, 'Sudan', 'SD', 'Sudanese Dinar', 'SDD', 0),
(203, 'Suriname', 'SR', 'Surinam Guilder', 'SRG', 0),
(204, 'Svalbard and Jan Mayen Islands', 'SJ', 'Norwegian Krone', 'NOK', 1),
(205, 'Swaziland', 'SZ', 'Swaziland Lilangeni', 'SZL', 0),
(206, 'Sweden', 'SE', 'Swedish Krona', 'SEK', 1),
(207, 'Switzerland', 'CH', 'Swiss Franc', 'CHF', 1),
(208, 'Syria', 'SY', 'Syrian Pound', 'SYP', 0),
(209, 'Taiwan', 'TW', 'Taiwan Dollar', 'TWD', 1),
(210, 'Tajikistan', 'TJ', 'Tajik Ruble', 'TJR', 0),
(211, 'Tanzania', 'TZ', 'Tanzanian Shilling', 'TZS', 1),
(212, 'Thailand', 'TH', 'Thai Baht', 'THB', 1),
(213, 'Togo', 'TG', 'CFA Franc BCEAO', 'XOF', 0),
(214, 'Tokelau', 'TK', 'New Zealand Dollar', 'NZD', 1),
(215, 'Tonga', 'TO', 'Tongan Pa&#699;anga', 'TOP', 0),
(216, 'Trinidad and Tobago', 'TT', 'Trinidad and Tobago Dollar', 'TTD', 1),
(217, 'Tunisia', 'TN', 'Tunisian Dollar', 'TND', 1),
(218, 'Turkey', 'TR', 'Turkish Lira', 'TRL', 0),
(219, 'Turkmenistan', 'TM', 'Manat', 'TMM', 0),
(220, 'Turks and Caicos Islands', 'TC', 'US Dollar', 'USD', 1),
(221, 'Tuvalu', 'TV', 'Australian Dollar', 'AUD', 1),
(222, 'U.K.', 'UK', 'Pound Sterling', 'GBP', 1),
(223, 'Uganda', 'UG', 'Uganda Shilling', 'UGS', 0),
(224, 'Ukraine', 'UA', 'Ukraine Hryvnia', 'UAG', 0),
(225, 'United Arab Emirates', 'AE', 'Arab Emirates Dirham', 'AED', 1),
(226, 'Uruguay', 'UY', 'Uruguayan Peso', 'UYP', 0),
(227, 'USA', 'US', 'US Dollar', 'USD', 1),
(228, 'USA Minor Outlying Islands', 'UM', 'US Dollar', 'USD', 1),
(229, 'Uzbekistan', 'UZ', 'Uzbekistan Sum', 'UZS', 1),
(230, 'Vanuatu', 'VU', 'Vanuatu Vatu', 'VUV', 0),
(231, 'Vatican', 'VA', 'Euro', 'EUR', 1),
(232, 'Venezuela', 'VE', 'Venezuelan Bolivar', 'VUB', 0),
(233, 'Vietnam', 'VN', 'Vietnamese Dong', 'VND', 1),
(234, 'Virgin Islands (British)', 'VG', 'US Dollar', 'USD', 1),
(235, 'Virgin Islands (USA)', 'VI', 'US Dollar', 'USD', 1),
(236, 'Wallis and Futuna Islands', 'WF', 'CFP Franc', 'XPF', 0),
(237, 'Western Sahara', 'EH', 'Moroccan Dirham', 'MAD', 1),
(238, 'Yemen', 'YE', 'Yemeni Rial', 'YER', 1),
(239, 'Yugoslavia', 'YU', 'Yugoslav New Dinar', 'YUN', 0),
(240, 'Zambia', 'ZM', 'Zambian Kwacha', 'ZMK', 1),
(241, 'Zimbabwe', 'ZW', 'Zimbabwe Dollar', 'ZWD', 0));
");
